name: Linters

on: [ workflow_call ]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.174.0
        with:
          bundler-cache: true
      # Add or replace any other lints here
      - name: Security audit dependencies
        run: bundle exec bundler-audit
      - name: Security audit application code
        run: bundle exec brakeman --quiet --confidence-level 2
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel
