name: Tests

on: [ workflow_call ]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: platform_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/platform_test"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.174.0
        with:
          bundler-cache: true
      - name: Install dependencies
        run: bundle install --jobs=4 --retry=3
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bundle exec rails db:schema:load
      # Add or replace test runners here
      - name: Run tests
        run: bundle exec rake
      - name: Check Database consistency
        run: bundle exec database_consistency -c .database_consistency.ignore.yml
